apiVersion: apps/v1
kind: Deployment
metadata:
  name: modbus-sim
  namespace: machine-platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: modbus-sim
  template:
    metadata:
      labels:
        app: modbus-sim
    spec:
      containers:
        - name: modbus-sim
          image: modbus-sim:local        # ðŸ‘ˆ your built image tag
          imagePullPolicy: IfNotPresent
          env:
            - name: MODBUS_HOST
              value: "0.0.0.0"
            - name: MODBUS_PORT
              value: "5020"
          ports:
            - containerPort: 5020

---
apiVersion: v1
kind: Service
metadata:
  name: modbus-sim
  namespace: machine-platform
spec:
  selector:
    app: modbus-sim
  ports:
    - name: modbus
      port: 5020
      targetPort: 5020
  type: ClusterIP
